// components/ImageUploadCard.vue
<template>
    <div class="card">
        <div class="card-image">
            <figure class="image is-square img-card">
                <img :src="props.src" />
            </figure>   
        </div>
        <footer class="card-footer">
            <a href="#" class="card-footer-item">Save</a>
            <a href="#" class="card-footer-item">Edit</a>
            <a href="#" class="card-footer-item">Delete</a>
        </footer>
    </div>
</template>

<script lang="ts" setup>
const props = defineProps({
    src: {
        type: [String],
    },
});
</script>

<style lang="scss" scoped>
.card {
    // width: 18rem ;
    // width: 100%;
    display: block;
}
.img-card {
    img {
        object-fit: cover;
    }

    &:hover {
        //filter: blur(1px);
        // background-color: rgba(26, 26, 26, 0.548);
    }
}
</style>

// src/components/imageUploadCard/ImageUploadCard.tsx
import style from "./ImageUploadCard.module.css";

const ImageUploadCard: React.FC<ImageUploadCardProps> = (props) => {
    return (
        <div className={`card ${style.cardBlock}`}>
            <div className="card-image">
                <figure className={`image is-square ${style.imgCard}`}>
                    <img src={props.src} />
                </figure>
            </div>
            <footer className="card-footer">
                <a href="#" className="card-footer-item">
                    Save
                </a>
                <a href="#" className="card-footer-item">
                    Edit
                </a>
                <a href="#" className="card-footer-item">
                    Delete
                </a>
            </footer>
        </div>
    );
};

export interface ImageUploadCardProps {
    src: string;
}
export default ImageUploadCard;
